### ISSUE TITLE
Infinite loading on lobby create/join

### ISSUE THREAD

**Issue by WulfBloodfang** [neomoth/NeoQOLPatchMod#2]
Narrowed down the issue to this QOL pack. As of the 1.0.1 hotfix the game will hang on an infinite loading screen when you try to create or join a lobby. Public, code-only, and solo/offline are all affected. Disabling the pack fixes the issue, enabling it breaks things again. Trying to uninstall and reinstall the pack doesn't solve the problem.

Edit: Narrowed down further, it is specifically an incompatibility with Lure. Having only those two mods enabled causes the hang, but using the QOL pack with any other combination of mods that does not include Lure or using it standalone does not hang the game.

**Comment by neomoth** [comment]
Fixed in latest patch
