### ISSUE TITLE
Crash with Webfishing+ as of v1.0.3

### ISSUE THREAD

**Issue by Jiroga** [neomoth/NeoQOLPatchMod#4]
When NeoQOL and Webfishing+ are installed, a fatal crash-to-desktop occurs.

Either loading the mod by itself, or going into Webfishing+'s configs and turning off the option _Menutweaks_ solves the issue.

GDWeave log & Godot logs:
[GDWeave.log](https://github.com/user-attachments/files/17549584/GDWeave.log)
[godot.log](https://github.com/user-attachments/files/17549587/godot.log)

**Comment by neomoth** [comment]
Issue is fixed and will be applied in next version
